### PR TITLE
Re-throw error thrown by Ext on failure to load missing controller class in Deft.mixin.Controllable

### PR DESCRIPTION
**Pull request by joshnesbitt**
Hi,

This is the first stab at fixing this. I took the chance to upgrade to Jasmine 1.2.0 now it's officially out too.

I'm having trouble building the CoffeeScript correctly, when I compile it seems there are more changes in the output than I'd expect. I'm using the following commands:

```
coffee --compile --output spec/js/ spec/coffee/
coffee --compile --output src/js/ src/coffee/
coffee --join build/deft-debug.js --compile src/
```

What command should I be using to compile the CoffeeScript? Apologies if this is obvious, I'm new to CoffeeScript.

Thanks,
Josh

### CODE REVIEW

**Comment by joshnesbitt** [comment]
This is related to issue #14.

**Comment by johnyanarella** [comment]
Looks great.  Excellent work - I especially appreciate that you provided a Jasmine test as well.

Thanks for updating Jasmine to the latest version as well.

Given the Sencha standard of omitting the "top-level function safety wrapper" (because application classes are typically combined for deployment using the Sencha SDK tools), we're using the --bare option when compiling. That's probably the culprit for the generated JavaScript discrepancies you mentioned.  The current .js files were built with CoffeeScript 1.3.1.  I intend to update to 1.3.3 today.

Leveraging CoffeeScript's --join option would be nice, but due to class order dependencies, we have been manually joining the files to date.  In the past (on other projects) I've run into issues with recursively joining files (and at one point submitted a pull request to CoffeeScript that was accepted but later clobbered by subsequent changes).

We're in sore need of a proper build script, and that's very high on the TODO list.  I'll generate the updated .js files and merge this in later today.

Much appreciated.

**Comment by joshnesbitt** [comment]
Ah, that explains the verbose changes then. I amended the existing test for the error being thrown, however if you'd like me to provide more please let me know. Testing the edge cases of the error that actually gets thrown is difficult, as it can vary depending on what part of the Ext.Loader.require mechanism fails.

**Comment by johnyanarella** [comment]
Scheduled for inclusion in v0.6.6.

**Comment by joshnesbitt** [comment]
Thanks for your help John.

**Comment by superstructor** [comment]
+1 this is a good change. catching everything and throwing only the generic error made debugging controller instantiation issues very difficult.

**Pull request closed without merging**
