### PR TITLE
Attempt to resolve issue/enhancement #12 by adding a preprocessor that merges...

### PR DESCRIPTION
**Pull request by brian428**
...injections instead of overriding superclass injections.

### CODE REVIEW

**Comment by brian428** [comment]
Added a number of specs to test the injection merge logic.

**Comment by johnyanarella** [comment]
Just wanted to update you on this - I pulled this down, reviewed it and started integrating it yesterday afternoon.

Overall, really great work.  I especially appreciate the inclusion of corresponding unit tests.

Before merging this into `master`, I am revising this slightly to leverage the Sencha class system's `onClassExtended` hooks to ensure that injection still occurs before the (subclass's) constructor fires even for subclasses that don't explicitly define `inject`.

I also anticipate that we will likely be deprecating and removing the `Deft.util.Injectable` and `Deft.util.Controllable` mixins before the release of 1.0 in favor of the simplicity of just handling the `inject` or `controller` annotations via Class preprocessors.  Consequently, I'll be revising this slightly to prepare for that as well.

**Comment by brian428** [comment]
Sounds great. I actually tried looking at onClassExtended() first, but to be honest I couldn't figure out how it worked and the documentation on that (and preprocessors in general) is really pretty pathetic heh. I'm almost finished with the Observer feature as well, so the onClassExtended() solution you add here will probably apply to that enhancement as well.

**Comment by johnyanarella** [comment]
Yeah, no kidding re: lack of documentation.

I've got it all working now (and fixed some other bugs I didn't realize existed along the way - such as how the `inject` and `controller` processors were being fired twice for every class in Ext JS 4.1 and Sencha Touch).

I'm going to take the lessons learned and revise the `controller` processor as well.

Consequently, I think v0.8 is going to be the version where the mixins will be deprecated.  Which means I'm also going to mean some revisions to the documentation...

That said, I expect I'll be merging this in sometime this weekend.

**Comment by johnyanarella** [comment]
Refactored the `inject` and `controller` class preprocessors to leverage `Ext.Base::override()` to intercept and override class constructors.

Added additional facade methods to `Deft.Class` to smooth out differences between Ext JS 4.0 and Ext JS 4.1 / Sencha Touch 2.0's APIs.

**Pull request merged**
